<?php

namespace Recipy\Extension\Twig;

use Symfony\Component\HttpFoundation\Session\Session;
use Twig_Extension;

/**
 * Class User
 * @package Recipy\Extension\Twig
 */
class User extends Twig_Extension
{
    /**
     * @var Session
     */
    protected $session;

    /**
     * User constructor.
     *
     * @param Session $session
     */
    public function __construct(Session $session)
    {
        $this->session = $session;
    }


    /**
     * {@inheritdoc}
     */
    public function getFunctions() : array
    {
        return [
            new \Twig_SimpleFunction('isLogged', function () {
                return $this->isLogged();
            }),
            new \Twig_SimpleFunction('user_username', function () {
                return $this->getUsername();
            })
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * Returns the login status
     *
     * @return bool
     */
    protected function isLogged() : bool
    {
        return !!$this->session->get('user')?? false;
    }

    /**
     * @return string
     */
    protected function getUsername() :string
    {
        return $this->session->get('user')['logins'] ?? 'unknow';
    }

    /**
     * Returns the name of the extension.
     *
     * @return string The extension name
     */
    public function getName() : string
    {
        return 'user';
    }
}
